name: CPack

on:
  push:
    branches:
    - master


jobs:
  Upload_archive_ZIP_files:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Prepare environment
        run: cmake --version

      - name: Build files
        shell: bash
        run: |
          mkdir _build && cd _build
          cmake -DFlag=ARC ..
          cmake --build .
          cpack -G ZIP

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v3.0.0
          release_name: Release v3.0.0
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 
            _build/solver-1.0.0-Linux.zip
          asset_name: artifacts
          asset_content_type: application/arch
          
